"""add cascade delete to todos FK

Revision ID: 20d96a64996d
Revises: 84f1fc815524
Create Date: 2026-03-22 03:39:36.647902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20d96a64996d'
down_revision: Union[str, Sequence[str], None] = '84f1fc815524'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('todos_owner_id_fkey'), 'todos', type_='foreignkey')
    op.create_foreign_key(None, 'todos', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'todos', type_='foreignkey')
    op.create_foreign_key(op.f('todos_owner_id_fkey'), 'todos', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###
